wikidot_username = "Notifier"
config_wiki = "notifications"
user_config_category = "notify"
wiki_config_category = "wiki"
gmail_username = "wikidotnotifier@gmail.com"
service_start_timestamp = 1627277777

[database]
driver = "notifier.database.drivers.mysql.MySqlDriver"
database_name = "wikidot_notifier"

[path]
# Paths:
# . -> cwd
# @ -> package root
# ? -> this config file
lang = "?/../lang.toml"

[log_dump_s3]
bucket_name = "wdnotifier"
object_key = "logs/recent_notifications.json"
